### ISSUE TITLE
FreeRADIUS

### ISSUE THREAD

**Issue by SirPrikol** [nerosketch/djing#2]
Приветствую, а вы не рассматривали возможность прикрутить к нему FreeRADIUS и посредством стандартных протоколов управлять шейпером на микротике?

**Comment by nerosketch** [comment]
Нет, ещё не рассматривал. Спасибо за вопрос, изучу этот вариант

**Comment by SirPrikol** [comment]
В принципе там не особо сложно :) Даже тут попалось решение, но там проект заброшен, можно оттуда взять принцип работы. Но, к сожалению, я не писатель, я просто й системщик :)

Проект с freeradius - https://github.com/AccessManager/access-manager
